#MYSQL_PASSWORD=$1
#if [ -z "${MYSQL_PASSWORD}" ]; then
#echo "MYSQL Password is missing"
#exit 1
#fi
#component=backend

#source common.sh

#Head "Disable NodeJS Default Version"
#dnf module disable nodejs -y &>>${log_file}
#Stat $?

#Head "Enable NodeJS 18 Version"
#dnf module enable nodejs:18 -y &>>${log_file}
#Stat $?

#Head "Install NodeJS"
#dnf install nodejs -y &>>/tmp/expe
#Stat $?

#Head "Configure Backend Service"
#cp backend.service /etc/systemd/system/backend.service &>>${log_file}
#Stat $?

#Head "Adding Application User"
#id expense &>>${log_file}

#if [$? -ne 0 ]; then
#useradd expense &>>${log_file}
#fi
#Stat $?



#Head "Remove existing App content"
#rm -rf $1 &>>${log_file}
#Stat $?

#Head "Create Application Directory"
#mkdir $1 &>>${log_file}
#Stat $?

#Head "Downloading Application Content"
#curl -o /tmp/${component}.zip https://expense-artifacts.s3.amazonaws.com/${component}.zip &>>${log_file}
#Stat $?

#cd $1

#Head "Extracting Application Content"
#unzip /tmp/${component}.zip &>>${log_file}
#Stat $?




#Head "Downloading Application Dependencies"
#npm install &>>${log_file}
#Stat $?

#Head "Reloading SystemD and Starting Backend Service"
#systemctl daemon-reload &>>${log_file}
#systemctl enable backend &>>${log_file}
#systemctl restart backend &>>${log_file}
#Stat $?
#Head "Install MySQL Client"
#dnf install mysql -y &>>${log_file}
#Stat $?

#Head "Load Schema"
#mysql -h 172.31.41.227 -uroot -p${MYSQL_PASSWORD} < /app/schema/backend.sql &>>${log_file}
#Stat $?

- name: Setup Backend
  hosts: all
  become: true
  tasks:
    - name: Disable NodeJs Module Default Version
      ansible.builtin.shell: dnf module disable nodejs -y

    - name: Enable NodeJs18 Module
      ansible.builtin.shell: dnf module enable nodejs:18 -y

    - name: Install NodeJs
      ansible.builtin.dnf:
        name: nodejs
        state: installed

    - name: Configure Backend Service
      ansible.builtin.copy:
        src: backend.service
        dest: /etc/systemd/system/backend.service

    - name: Add a application user
      ansible.builtin.user:
        name: expense

    - name: Remove existing App content
      ansible.builtin.file:
        path: /app
        state: absent

    - name: Create Application Directory
      ansible.builtin.file:
        path: /app
        state: directory

    - name: Download and extract App Content
      ansible.builtin.unarchive:
        src: https://expense-artifacts.s3.amazonaws.com/backend.zip
        dest: /app
        remote_src: yes

    - name: Download Dependencies
      community.general.npm:
        path: /app

    - name: Reloading SystemD and start Backend Service
      ansible.builtin.systemd_service:
        name: backend
        enabled: yes
        state: restarted

    - name: Install MySQL Client
      ansible.builtin.dnf:
        name: mysql
        state: installed


    - name: Install MySQL Client
      ansible.builtin.dnf:
        name: python3-PyMySQL
        state: installed

    - name: Load Schema
      community.mysql.mysql_db:
        state: import
        name: all
        target: /app/schema/backend.sql
        login_user: root
        login_password: ExpenseApp@1
        login_host: 172.31.32.151



