#MYSQL_PASSWORD=$1
#if [ -z "${MYSQL_PASSWORD}" ]; then
#echo "MYSQL Password is missing"
#exit 1
#fi
#dnf module disable mysql -y

#cp mysql.repo /etc/yum.repos.d/mysql.repo

#dnf install mysql-community-server -y

#systemctl enable mysqld
#systemctl start mysqld




#mysql_secure_installation --set-root-pass ${MYSQL_PASSWORD}

- name: Expense Project Setup
  hosts: all
  become: yes
  roles:
    -  "{{ service_name }}"






