- name: Disable NodeJs Module Default Version
  ansible.builtin.shell: dnf module disable nodejs -y

- name: Enable NodeJs18 Module
  ansible.builtin.shell: dnf module enable nodejs:18 -y

- name: Install NodeJs
  ansible.builtin.dnf:
    name: nodejs
    state: installed

- name: Configure Backend Service
  ansible.builtin.copy:
    src: backend.service
    dest: /etc/systemd/system/backend.service

- name: Add a application user
  ansible.builtin.user:
    name: expense

- name: Remove existing App content
  ansible.builtin.file:
    path: /app
    state: absent

- name: Create Application Directory
  ansible.builtin.file:
    path: /app
    state: directory

- name: Download and extract App Content
  ansible.builtin.unarchive:
    src: https://expense-artifacts.s3.amazonaws.com/backend.zip
    dest: /app
    remote_src: yes

- name: Download Dependencies
  community.general.npm:
    path: /app

- name: Reloading SystemD and start Backend Service
  ansible.builtin.systemd_service:
    name: backend
    enabled: yes
    state: restarted

- name: Install MySQL Client
  ansible.builtin.dnf:
    name: mysql
    state: installed


- name: Install MySQL Client
  ansible.builtin.dnf:
    name: python3-PyMySQL
    state: installed



- name: Load Schema
  community.mysql.mysql_db:
    state: import
    name: all
    target: /app/schema/backend.sql
    login_user: root
    login_password: ExpenseApp@1
    login_host: 172.31.32.151
