- name: Install Nginx
  ansible.builtin.dnf:
    name: httpd
    state: installed

- name: Copy file with owner and permissions
  ansible.builtin.copy:
    src: expense.conf
    dest: /etc/nginx/default.d/expense.conf

- name: App Pre-requisites
  ansible.builtin.include_role:
    name: common
    tasks_from: app_prereq



- name: Start Nginx Service
  ansible.builtin.service:
    name: nginx
    enabled: yes
    state: restarted